server:
  port: 10001

spring:
  kafka:
    #bootstrap-servers: localhost:9091
    producer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: 1
        spring:
          json:
            add:
              type:
                headers: false

topic:
  send-msg: send-msg-event